"""


You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"



"""

s = "abcd"
t = "abcde"

# s = "a"
# t = "aa"

s_set = set(s)
t_set = set(t)

op = S = ''.join(s_set.symmetric_difference(t_set))
print(op)

# s_lis = list(s)
# t_lis = list(t)

# # set.symmetric_difference_update


